dataset:
  train:
    name: mixed
    prob_ls: [0.9, 0.1]
    dataset_list:
    - name: hypersim
      disp_name: hypersim_train
      dir: hypersim
      filenames: datasets/hypersim/hypersim/jsons_depth_normal
      resize_to_hw:
      - 480
      - 640
    - name: vkitti
      disp_name: vkitti_train
      dir: vkitti
      filenames: datasets/vkitti/virtual_kitti/jsons_20240920
      kitti_bm_crop: true
      valid_mask_crop: null